### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/ompd-mod#1]
It complains about mysql not being activated in php.  Ompd works without problems.  Just curious if I am missing something?

**Comment by othmar52** [comment]
maybe `php-pdo` and `php-mysqli` is missing!?

please consider to use `O!MPD` or [sliMpd](https://github.com/othmar52/slimpd) because the development of `ompd-mod` is discontinued.

**Comment by killhellokitty** [comment]
Thank you for getting back in touch with me.  sliMpd looks pretty cool, so
i've decided to give it a try.  I'm stuck though.  I get this error message
when I enter: cli-update.php

_PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc()
on boolean in /srv/http/slimpd/php/modules/importer/main.php:649_
_Stack trace:_
_#0 /srv/http/slimpd/cli-update.php(114): Slimpd\Importer->checkQue()_
_#1 [internal function]: {closure}()_
_#2 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Route.php(468):
call_user_func_array(Object(Closure), Array)_
_#3 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Slim.php(1357):
Slim\Route->dispatch()_
_#4 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Middleware/Flash.php(85):
Slim\Slim->call()_
_#5
/srv/http/slimpd/vendor-dist/slim/slim/Slim/Middleware/MethodOverride.php(92):
Slim\Middleware\Flash->call()_
_#6 /srv/http/slimpd/vendor-dist/slim/slim/Slim/Slim.php(1302):
Slim\Middleware\MethodOverride->call()_
_#7 /srv/http/slimpd/cli-update.php(145): Slim\Slim->run()_
_#8 {main}_
-  thrown in /srv/http/slimpd/php/modules/importer/main.php on line 649*

I don't know anything about PHP, so I am totally lost.  Perhaps I
miss-configured something else?
Another thing that has me confused is that I am using 'acl' for
permissions; to allow it access to my Music folder in my home directory and
I haven't been able to get that to work at all even with O!mpd.  I have
both O!mpd and sliMpd in 'http's' user and group.  Also Mpd is configured
for user in ~/.config/mpd, but I have sym-linked it to /var/lib/mpd

_getfacl: Removing leading '/' from absolute path names_
_# file: home/jo-shva/Music/_
_# owner: jo-shva_
_# group: users_
_user::rwx_
_user:http:--x_
_group::r-x_
_mask::r-x_
_other::r-x_

I'm including a screen-shot of sliMpd @ localhost; as well as the
config_local.ini, just in case they offer up some insight.
I'm asking just in case you have some words of wisdom to share.  Otherwise
any help you can offer to help me to get sliMpd working would be greatly
appreciated!

Regards,
Josh Brown-Williams

**Comment by othmar52** [comment]
I have updated [system-requirements and installation-instructions](https://github.com/othmar52/slimpd/wiki/Installation). Would be great if you can give it another try...

Maybe your permission problem is caused by [open_basedir](http://php.net/manual/en/ini.core.php#ini.open-basedir)

please open another issue in the slimpd-repo
